export {default as Teacher} from "./Images/teacher.png";
export {default as Teacher1} from "./Images/teacher1.png";
export {default as Teacher2} from "./Images/teacher2.png";
export {default as Teacher3} from "./Images/teacher3.png";
export {default as Teacher4} from "./Images/teacher4.png";
export {default as Teacher5} from "./Images/teacher5.png";
export {default as Teacher_pupil} from "./Images/teacher_pupil.png";
export {default as Microphone} from "./Images/microphone.png";
// export { default as Microphone } from "../UI/Images/microphone.jpeg";
export {default as Study} from "./Images/study.png";
export {default as Logo} from "./Images/logo.png";
export {default as LandingPage_bg} from "./Images/landingPage_bg.png";
export {default as LandingPage} from "./Images/landingPage.png";
export {default as Smile} from "./Images/smile.png";
export {default as Login} from "./Images/Rectangle.png";
